-- MySQL Script generated by MySQL Workbench
-- 06/23/15 08:55:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Itesco
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Itesco` ;

-- -----------------------------------------------------
-- Schema Itesco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Itesco` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Itesco` ;

-- -----------------------------------------------------
-- Table `Itesco`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Itesco`.`alumno` (
  `id_alumno` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(50) NULL COMMENT '',
  `carrera` VARCHAR(50) NULL COMMENT '',
  `nivel` VARCHAR(50) NULL COMMENT '',
  PRIMARY KEY (`id_alumno`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Itesco`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Itesco`.`empleado` (
  `idempleado` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(50) NULL COMMENT '',
  `cargo` VARCHAR(30) NULL COMMENT '',
  `pass` VARCHAR(8) NULL COMMENT '',
  PRIMARY KEY (`idempleado`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Itesco`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Itesco`.`libro` (
  `id_libro` INT NOT NULL COMMENT '',
  `titulo` VARCHAR(50) NULL COMMENT '',
  `editorial` VARCHAR(30) NULL COMMENT '',
  `autor` VARCHAR(50) NULL COMMENT '',
  `url` VARCHAR(50) NULL COMMENT '',
  `fecha` VARCHAR(50) NULL COMMENT '',
  PRIMARY KEY (`id_libro`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Itesco`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Itesco`.`prestamo` (
  `id_prestamo` INT NOT NULL COMMENT '',
  `id_alumno` INT NULL COMMENT '',
  `id_libro` INT NULL COMMENT '',
  `fecha` VARCHAR(50) NULL COMMENT '',
  PRIMARY KEY (`id_prestamo`)  COMMENT '',
  CONSTRAINT `id_alumno`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `Itesco`.`alumno` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_libro`
    FOREIGN KEY (`id_libro`)
    REFERENCES `Itesco`.`libro` (`id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_alumno_idx` ON `Itesco`.`prestamo` (`id_alumno` ASC)  COMMENT '';

CREATE INDEX `id_libro_idx` ON `Itesco`.`prestamo` (`id_libro` ASC)  COMMENT '';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
